services:
  # ============================= Databases =============================
  skilltag-db:
    image: postgres:latest
    container_name: company-skilltag-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: skilltag_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d skilltag_db || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
